name: deploy
on:
  push: 
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        
    - name: Build Spring Boot Application
      run: ./mvnw package -DskipTests=true

    - name: Build Docker Image
      run: |
        docker build -t vasquezdev/ms-client-image:latest
        docker login -u ${{ secrets.DOCKER_USERNAME }} -P ${{ secrets.DOCKER_PASSWORD }}
        docker push vasquezdev/ms-client-image:latest